baseURL: ""
languageCode: en-us
title: tinega gideon

theme: PaperMod
enableEmoji: true


params:
# blog post configuration params
  ShowReadingTime: true

# home welcome block configuration params
  homeInfoParams:
    Title: Hello ðŸ‘‹
    Content: 

            Welcome to my blog.

            - I'm passionate about **networking**, **cloud computing**, **linux** and **network security**.

            - ðŸŽ“ Computer science graduate.

            - Checkout my Blog Posts here & [Dev.to](https://dev.to/tinegagideon)

            - [Say hi on twitter](https://twitter.com/tinega_)

            

  socialIcons:        
        
        - name: dev
          url:  https://dev.to/tinegagideon
        - name: linkedin
          url:  https://www.linkedin.com/in/tinegagideon
        - name: github
          url:  https://github.com/tin3ga
        - name: tryhackme
          url:  https://tryhackme.com/p/tinega
        - name: cv
          url: https://drive.google.com/file/d/1fum6OZG81sYGTU23FHGoZPLoEEUvaySe/view?usp=sharing

# menu nav panel
menu:
  main:
    - name: Tags
      url:  /tags/
      weight: 50
    - name: Experience
      url:  /experience/
      weight: 30
    - name: Search
      url:  /search/
      weight: 40
    - name: Dev
      url: https://dev.to/tinegagideon



